version = 0.1

[dev.deploy.parameters]
stack_name = "code-x-v0"
resolve_s3 = true
s3_prefix = "code-x-v0"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "S3BucketName=\"devsarena\" Environment=\"dev\""
image_repositories = []
