apiVersion: v1
kind: ConfigMap
metadata:
  name: language-init-commands
  namespace: devsarena
data:
  # Node.js applications don't need init commands as they run npm install via start commands
  # react: ""
  # node: ""
  # node-express: ""
